# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
    app.service.project:
        class: AppBundle\Service\ProjectService
        arguments: ["@doctrine.orm.default_entity_manager"]
    app.controller.migrate_project:
        class: AppBundle\Controller\Gitlab\MigrateProjectController
        arguments: ["@app.service.project"]
        calls:
          - ["setContainer", ["@service_container"]]
